# Generated by Django 2.2.1 on 2019-06-08 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190608_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='topic',
            field=models.CharField(max_length=40, verbose_name='Тема'),
        ),
    ]
