# Generated by Django 2.2.1 on 2019-06-08 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190608_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='photo',
            field=models.CharField(max_length=20, null=True, verbose_name='Фотография'),
        ),
    ]
