# Generated by Django 2.2.1 on 2019-06-08 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190608_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='topic',
            field=models.CharField(max_length=100, verbose_name='Тема'),
        ),
    ]
