# Generated by Django 2.2.1 on 2019-06-08 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190608_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='photo',
            field=models.CharField(max_length=100, null=True, verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='course',
            name='topic',
            field=models.CharField(max_length=50, verbose_name='Тема'),
        ),
    ]
