# Generated by Django 2.2.1 on 2019-06-10 09:14

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190608_2215'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Course')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
                'db_table': 'lessons',
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.Lesson')),
                ('questions', django.contrib.postgres.fields.jsonb.JSONField()),
                ('answers', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            bases=('api.lesson',),
        ),
        migrations.CreateModel(
            name='Theory',
            fields=[
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.Lesson')),
                ('theory_link', models.URLField(null=True)),
            ],
            bases=('api.lesson',),
        ),
    ]
