# Generated by Django 2.2.1 on 2019-06-10 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_lesson_quiz_theory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name': 'тест', 'verbose_name_plural': 'тесты'},
        ),
        migrations.AlterModelOptions(
            name='theory',
            options={'verbose_name': 'теория', 'verbose_name_plural': 'теория'},
        ),
        migrations.AlterModelTable(
            name='quiz',
            table='quizes',
        ),
        migrations.AlterModelTable(
            name='theory',
            table='lections',
        ),
    ]
