# Generated by Django 2.2.1 on 2019-06-10 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20190610_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_lessons', to='api.Course'),
        ),
        migrations.AlterField(
            model_name='theory',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theory_lessons', to='api.Course'),
        ),
    ]
