# Generated by Django 2.2.2 on 2019-06-12 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0012_auto_20190610_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='time',
            field=models.IntegerField(default=1, verbose_name='Время прохождения в часах'),
        ),
        migrations.AddField(
            model_name='course',
            name='type',
            field=models.CharField(default='Free', max_length=50, verbose_name='Тип курса'),
        ),
        migrations.AddField(
            model_name='theory',
            name='link_description',
            field=models.CharField(max_length=100, null=True, verbose_name='Описание ссылки'),
        ),
        migrations.CreateModel(
            name='ChatBot',
            fields=[
                ('login', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='Логин')),
                ('bot_id', models.CharField(max_length=20, null=True, verbose_name='id')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
