# Generated by Django 2.2.2 on 2019-06-12 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20190612_1619'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatbot',
            options={'verbose_name': 'бот', 'verbose_name_plural': 'боты'},
        ),
        migrations.AlterModelTable(
            name='chatbot',
            table='televot',
        ),
    ]
