# Generated by Django 2.2.2 on 2019-06-12 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20190612_1655'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='chatbot',
            table='telebot',
        ),
    ]
